// vocabulary.js
const VOCABULARY_SETS = {
  "dong_vat": {
    name: "Các loài Động vật 🐾",
    words: [
      { vi: 'chó', en: 'Dog', ko: '개', sound: 'gâu gâu' },
      { vi: 'mèo', en: 'Cat', ko: '고양이', sound: 'meo meo' },
      { vi: 'gà', en: 'Chicken', ko: '닭', sound: 'cục tác' },
      { vi: 'vịt', en: 'Duck', ko: '오리', sound: 'quạc quạc' },
      { vi: 'bò', en: 'Cow', ko: '소', sound: 'ùm bò' },
      { vi: 'heo', en: 'Pig', ko: '돼지', sound: 'ụt ịt' },
      { vi: 'cừu', en: 'Sheep', ko: '양', sound: 'be be' },
      { vi: 'ngựa', en: 'Horse', ko: '말', sound: 'hí hí' },
      { vi: 'voi', en: 'Elephant', ko: '코끼리' },
      { vi: 'khỉ', en: 'Monkey', ko: '원숭이', sound: 'khẹc khẹc' },
      { vi: 'sư tử', en: 'Lion', ko: '사자', sound: 'gầm' },
      { vi: 'hổ', en: 'Tiger', ko: '호랑이' },
      { vi: 'gấu', en: 'Bear', ko: '곰' },
      { vi: 'cáo', en: 'Fox', ko: '여우' },
      { vi: 'thỏ', en: 'Rabbit', ko: '토끼' },
      { vi: 'hươu cao cổ', en: 'Giraffe', ko: '기린' },
      { vi: 'gấu trúc', en: 'Panda', ko: '판다' },
      { vi: 'ngựa vằn', en: 'Zebra', ko: '얼룩말' },
      { vi: 'cá heo', en: 'Dolphin', ko: '돌고래' },
      { vi: 'cá mập', en: 'Shark', ko: '상어' },
      { vi: 'bạch tuộc', en: 'Octopus', ko: '문어' },
      { vi: 'rùa', en: 'Turtle', ko: '거북이' },
      { vi: 'chim cánh cụt', en: 'Penguin', ko: '펭귄' },
      { vi: 'ếch', en: 'Frog', ko: '개구리', sound: 'ộp ộp' },
      { vi: 'rắn', en: 'Snake', ko: '뱀', sound: 'xì' },
      { vi: 'ong', en: 'Bee', ko: '벌', sound: 'vo ve' },
      { vi: 'bướm', en: 'Butterfly', ko: '나비' },
      { vi: 'chuột', en: 'Mouse', ko: '쥐' },
      { vi: 'cá sấu', en: 'Crocodile', ko: '악어' },
      { vi: 'hà mã', en: 'Hippopotamus', ko: '하마' },
      { vi: 'chim', en: 'Bird', ko: '새' },
      { vi: 'cú', en: 'Owl', ko: '부엉이' }
    ]
  },
  "thuc_vat": {
    name: "Các loại Thực vật 🌳",
    words: [
      { vi: 'cà rốt', en: 'Carrot', ko: '당근' },
      { vi: 'cà chua', en: 'Tomato', ko: '토마토' },
      { vi: 'quả táo', en: 'Apple', ko: '사과' },
      { vi: 'quả cam', en: 'Orange', ko: '오렌지' },
      { vi: 'quả dưa hấu', en: 'Watermelon', ko: '수박' },
      { vi: 'bông cải xanh', en: 'Broccoli', ko: '브로콜리' },
      { vi: 'cây nấm', en: 'Mushroom', ko: '버섯' },
      { vi: 'củ khoai tây', en: 'Potato', ko: '감자' },
      { vi: 'bắp ngô', en: 'Corn', ko: '옥수수' },
      { vi: 'quả dâu tây', en: 'Strawberry', ko: '딸기' },
      { vi: 'quả nho', en: 'Grape', ko: '포도' },
      { vi: 'quả chanh', en: 'Lemon', ko: '레몬' },
      { vi: 'hành tây', en: 'Onion', ko: '양파' },
      { vi: 'củ tỏi', en: 'Garlic', ko: '마늘' },
      { vi: 'quả ớt', en: 'Chili pepper', ko: '고추' },
      { vi: 'quả dứa', en: 'Pineapple', ko: '파인애플' },
      { vi: 'quả bơ', en: 'Avocado', ko: '아보카도' },
      { vi: 'quả dưa chuột', en: 'Cucumber', ko: '오이' },
      { vi: 'quả chuối', en: 'Banana', ko: '바나나' },
      { vi: 'cải bắp', en: 'Cabbage', ko: '양배추' },
      { vi: 'quả xoài', en: 'Mango', ko: '망고' },
      { vi: 'cây', en: 'Tree', ko: '나무' },
      { vi: 'hoa', en: 'Flower', ko: '꽃' },
      { vi: 'lá', en: 'Leaf', ko: '잎' }
    ]
  },
    "mau_sac": {
    name: "Màu sắc rực rỡ 🎨",
    words: [
      { vi: 'màu đỏ', en: 'Red', ko: '빨간색' },
      { vi: 'màu vàng', en: 'Yellow', ko: '노란색' },
      { vi: 'màu xanh lá', en: 'Green', ko: '초록색' },
      { vi: 'màu xanh dương', en: 'Blue', ko: '파란색' },
      { vi: 'màu cam', en: 'Orange', ko: '주황색' },
      { vi: 'màu tím', en: 'Purple', ko: '보라색' },
      { vi: 'màu hồng', en: 'Pink', ko: '분홍색' },
      { vi: 'màu đen', en: 'Black', ko: '검은색' },
      { vi: 'màu trắng', en: 'White', ko: '흰색' },
      { vi: 'màu xám', en: 'Gray', ko: '회색' },
      { vi: 'màu nâu', en: 'Brown', ko: '갈색' },
      { vi: 'màu bạc', en: 'Silver', ko: '은색' },
      { vi: 'màu vàng kim', en: 'Gold', ko: '금색' },
      { vi: 'màu be', en: 'Beige', ko: '베이지색' }
    ]
  },
  "gia_dinh": {
    name: "Gia đình yêu thương ❤️",
    words: [
      { vi: 'bố', en: 'Father', ko: '아버지' },
      { vi: 'mẹ', en: 'Mother', ko: '어머니' },
      { vi: 'anh trai', en: 'Older brother', ko: '형/오빠' },
      { vi: 'chị gái', en: 'Older sister', ko: '누나/언니' },
      { vi: 'em trai', en: 'Younger brother', ko: '남동생' },
      { vi: 'em gái', en: 'Younger sister', ko: '여동생' },
      { vi: 'ông', en: 'Grandfather', ko: '할아버지' },
      { vi: 'bà', en: 'Grandmother', ko: '할머니' },
      { vi: 'gia đình', en: 'Family', ko: '가족' },
      { vi: 'con trai', en: 'Son', ko: '아들' },
      { vi: 'con gái', en: 'Daughter', ko: '딸' },
      { vi: 'chú', en: 'Uncle', ko: '삼촌' },
      { vi: 'cô', en: 'Aunt', ko: '고모' },
      { vi: 'dì', en: 'Aunt (mother\'s sister)', ko: '이모' },
      { vi: 'em bé', en: 'Baby', ko: '아기' }
    ]
  },
  "nha_bep": {
    name: "Đồ dùng nhà bếp 🍳",
    words: [
      { vi: 'cái bát', en: 'Bowl', ko: '그릇' },
      { vi: 'đôi đũa', en: 'Chopsticks', ko: '젓가락' },
      { vi: 'cái thìa', en: 'Spoon', ko: '숟가락' },
      { vi: 'cái dĩa', en: 'Fork', ko: '포크' },
      { vi: 'con dao', en: 'Knife', ko: '칼' },
      { vi: 'cái thớt', en: 'Cutting board', ko: '도마' },
      { vi: 'cái nồi', en: 'Pot', ko: '냄비' },
      { vi: 'cái chảo', en: 'Pan', ko: '프라이팬' },
      { vi: 'cái cốc', en: 'Cup', ko: '컵' },
      { vi: 'cái đĩa', en: 'Plate', ko: '접시' },
      { vi: 'tủ lạnh', en: 'Refrigerator', ko: '냉장고' },
      { vi: 'bếp ga', en: 'Stove', ko: '가스레인지' },
      { vi: 'lò vi sóng', en: 'Microwave', ko: '전자레인지' },
      { vi: 'ấm đun nước', en: 'Kettle', ko: '주전자' },
      { vi: 'bồn rửa bát', en: 'Sink', ko: '싱크대' }
    ]
  },
  "the_gioi": {
    name: "Thế giới quanh ta 🌎",
    words: [
      { vi: 'mặt trời', en: 'Sun', ko: '해' },
      { vi: 'mặt trăng', en: 'Moon', ko: '달' },
      { vi: 'ngôi sao', en: 'Star', ko: '별' },
      { vi: 'bầu trời', en: 'Sky', ko: '하늘' },
      { vi: 'đám mây', en: 'Cloud', ko: '구름' },
      { vi: 'cơn mưa', en: 'Rain', ko: '비' },
      { vi: 'ngọn núi', en: 'Mountain', ko: '산' },
      { vi: 'dòng sông', en: 'River', ko: '강' },
      { vi: 'biển', en: 'Sea', ko: '바다' },
      { vi: 'cái cây', en: 'Tree', ko: '나무' },
      { vi: 'bông hoa', en: 'Flower', ko: '꽃' },
      { vi: 'bãi cỏ', en: 'Grass', ko: '잔디' },
      { vi: 'trái đất', en: 'Earth', ko: '지구' },
      { vi: 'ngọn lửa', en: 'Fire', ko: '불' },
      { vi: 'nước', en: 'Water', ko: '물' }
    ]
  },
  "do_vat": {
    name: "Đồ vật Quen thuộc ✏️",
    words: [
      { vi: 'cái bàn', en: 'Table', ko: '책상' },
      { vi: 'cái ghế', en: 'Chair', ko: '의자' },
      { vi: 'quyển sách', en: 'Book', ko: '책' },
      { vi: 'cây bút', en: 'Pen', ko: '펜' },
      { vi: 'cái giường', en: 'Bed', ko: '침대' },
      { vi: 'ô tô', en: 'Car', ko: '자동차' },
      { vi: 'xe đạp', en: 'Bicycle', ko: '자전거' },
      { vi: 'máy bay', en: 'Airplane', ko: '비행기' },
      { vi: 'ngôi nhà', en: 'House', ko: '집' },
      { vi: 'quả bóng', en: 'Ball', ko: '공' },
      { vi: 'tivi', en: 'Television', ko: '텔레비전' },
      { vi: 'điện thoại', en: 'Phone', ko: '전화기' },
      { vi: 'máy tính', en: 'Computer', ko: '컴퓨터' },
      { vi: 'đồng hồ', en: 'Clock', ko: '시계' },
      { vi: 'chìa khóa', en: 'Key', ko: '열쇠' },
      { vi: 'cái mũ', en: 'Hat', ko: '모자' },
      { vi: 'đôi giày', en: 'Shoes', ko: '신발' },
      { vi: 'cửa sổ', en: 'Window', ko: '창문' },
      { vi: 'cửa ra vào', en: 'Door', ko: '문' },
      { vi: 'cái kéo', en: 'Scissors', ko: '가위' },
      { vi: 'cái gương', en: 'Mirror', ko: '거울' },
      { vi: 'cái túi', en: 'Bag', ko: '가방' }
    ]
  }
};
